capital_cities = [
    {"city": "London",
     "country": "England",
     "population": 9046000,
     },
    {"city": "Kabul",
     "country": "Afghanistan",
     "population": 4012000,
     },
    {"city": "Paris",
     "country": "France",
     "population": 10901000,
     },
    {"city": "Luanda",
     "country": "Angola",
     "population": 7774000,
     },
    {"city": "Vienna",
     "country": "Austria",
     "population": 1901000,
     },
    {"city": "Zagreb",
     "country": "Croatia",
     "population": 686000,
     },
    {"city": "Havana",
     "country": "Cuba",
     "population": 2136000,
     },
    {"city": "Addis Ababa",
     "country": "Ethiopia",
     "population": 4400000,
     },
]
